### ISSUE TITLE
Can this project be used in browser environment?

### ISSUE THREAD

**Issue by mehrdaad** [OpenMarshal/npm-WebDAV-Client#1]

**Comment by AdrienCastex** [comment]
Hello,

It can be used in browser environment.
I added a file to use it easily in a web browser, but keep in mind that it might not be optimized for browser environment. You can find the browser version at `lib/browserified.js`.

Here is a little sample of a usage :

```html
<html>
    <head>
        <script src="lib/browserified.js"></script>
        <script>
            const connection = new window.webdavClient.Connection('http://my-webdav-server:1900');

            connection.get('/path/of/my/file.txt', (e, content) => {
                if(e)
                    throw e;
                
                console.log(content);
            });
        </script>
    </head>
    <body></body>
</html>
```

As you can see, the `lib/browserified.js` file will load the `Connection` class into the variable `window.webdavClient`.

I let you close the issue if you think that I answered your question.
Thank you for your contribution.

**Comment by mehrdaad** [comment]
@AdrienCastex how about installing it via ``npm``?  
Also why is the package globally available in window variable?  Don't you think it would be better to export a function from package to import/require and then call it accordingly?

**Comment by AdrienCastex** [comment]
You can install it via `npm` with `npm install webdav-client`.

The package is globally available in `window` to allow you to do `new webdavClient.Connection(...)` in a web browser (which is the same as `webdavClient.Connection(...)`, because, by default, it will look in the `window` global "variable").

The package can be used with `require`/`import` if you do so :
```typescript
import * as webdavClient from 'webdav-client'
// or
import { Connection } from 'webdav-client'
// or
const webdavClient = require('webdav-client');
```

I hope that helped you.

**Comment by mehrdaad** [comment]
For sure it helped me. maybe for future visitors, it would be nice to leave it in them main README file along with the documentation and api. thank you.

**Comment by AdrienCastex** [comment]
You are right.
I updated the `README.md` to talk about it.

Thank you.

**Comment by georgii-ivanov** [comment]
It would be cool include browser binary upload (put) documentation.
Because I'm sure it used in many cases.

Is there any chance to use File API + Node.JS stream for browser upload?
